
package GUI.quankho;

import DAO.QuanKhoDAO;
import DTO.DSNguyenLieu;
import DTO.MONAN;
import DTO.NGUYENLIEU;
import DTO.THANHPHAN;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Func_class;

/**
 *
 * @author ADMIN
 */
public class ThanhPhanDialog extends javax.swing.JDialog {
QuanKhoDAO kn=new QuanKhoDAO();
    DefaultTableModel dtm=new DefaultTableModel();
    DSNguyenLieu dsnl;
    String dsMaNL[]=new String[10];
    String dsTenNL[]=new String[10];
    Float dsSLNL[]=new Float[10];
    MONAN monAn;
    int index=0;
    int tinhTrang;
    QKMonAnJPanel panel;
    Func_class func=new Func_class();
    public ThanhPhanDialog(java.awt.Frame parent, boolean modal,MONAN ma,int tt,QKMonAnJPanel panel) {
        super(parent, modal);
        this.tinhTrang = tt;
        this.panel = panel;
        this.monAn = ma;
        initComponents();
        bangNL.setModel(dtm);
        setBangNL();
        func.centerTable(bangNL);
        func.setUpTable(bangNL,jScrollPane1);
        func.setUpJScrollPane(jScrollPane2);
        func.setUpBtnTwo(addNL, Color.GREEN, Color.GREEN, Color.WHITE, 14);
        func.setUpBtnTwo(clearNL, Color.RED, Color.RED, Color.WHITE, 14);
        func.setUpBtnTwo(conFirm, Color.CYAN, Color.CYAN, Color.WHITE, 14);
        if (tt == 1) {
            THANHPHAN tpp = new THANHPHAN();
            kn.layTP(monAn.getMaMA(), tpp);
            dsMaNL = tpp.getMaNL();
            dsSLNL = tpp.getSoLuong();
            index = tpp.getN();
            for (int i = 0; i < index; i++) {
                System.out.println(dsMaNL[i] + " " + dsSLNL[i]);
            }
            for (int i = 0; i < index; i++) {
                for (int k = 0; k < bangNL.getRowCount(); k++) {
                    if (dsMaNL[i].equals((String) bangNL.getValueAt(k, 0))) {
                        dsTenNL[i] = (String) bangNL.getValueAt(k, 1);
                    }
                }
            }
        }
        setCongThuc();
        this.setTitle("Lập công thức món ăn");
        setLocationRelativeTo(null);
    }
    private void setBangNL(){ 
        dsnl=new DSNguyenLieu();
        kn.layNL(dsnl);
        System.out.println(dsnl.getDSNL().size());
        dtm.setRowCount(0);
        if(dtm.getColumnCount()==0){ 
            dtm.addColumn("Mã NL");
            dtm.addColumn("Tên NL");
            dtm.addColumn("Mô Tả");
        }
        int count =0;
        for(NGUYENLIEU a:dsnl.getDSNL()){ 
            if(a.getTrangThai()!=0)
            dtm.addRow(new Object[]{a.getMaNL(),a.getTenNL(),a.getMoTa()});
            
        }
            
    }
    private void setCongThuc() {
        StringBuilder sb = new StringBuilder();
        sb.append("Công Thức: ").append(monAn.getTenMA()).append("\n\n");
        sb.append(String.format("%-4s %-10s %-10s %-6s\n", "STT", "Mã NL", "Số lượng", "Đơn vị"));
        sb.append("--------------------------------------------------\n");

        for (int i = 0; i < index; i++) {
            if (dsMaNL[i] != null) {
                sb.append(String.format("%-4d %-10s %-10.1f %-6s\n", i + 1, dsMaNL[i], dsSLNL[i], "gam"));
            }
        }

        congthuc.setFont(new Font("Monospaced", Font.PLAIN, 12)); // Font chữ đều để căn dòng chính xác
        congthuc.setText(sb.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangNL = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tenNL = new javax.swing.JLabel();
        slNL = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        congthuc = new javax.swing.JTextArea();
        addNL = new javax.swing.JButton();
        conFirm = new javax.swing.JButton();
        clearNL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bangNL.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        bangNL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangNLMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bangNL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel1.setText("Tên Nguyên Liệu");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setText("Số Lượng");

        tenNL.setBackground(new java.awt.Color(255, 255, 255));
        tenNL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));
        tenNL.setOpaque(true);

        slNL.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));

        congthuc.setColumns(20);
        congthuc.setRows(5);
        jScrollPane2.setViewportView(congthuc);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slNL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tenNL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tenNL, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        addNL.setText("Thêm");
        addNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNLActionPerformed(evt);
            }
        });

        conFirm.setText("Xác Nhận");
        conFirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conFirmActionPerformed(evt);
            }
        });

        clearNL.setText("Clear");
        clearNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearNLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addNL, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(conFirm, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearNL, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clearNL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(conFirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bangNLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangNLMouseClicked
        int row = bangNL.getSelectedRow();
        tenNL.setText((String) bangNL.getValueAt(row,1));
    }//GEN-LAST:event_bangNLMouseClicked

    private void conFirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conFirmActionPerformed
        THANHPHAN tp=new THANHPHAN();
        tp.setMaMA(monAn.getMaMA());
        tp.setMaNL(dsMaNL);
        tp.setSoLuong(dsSLNL);
        tp.setN(index);
        if(tinhTrang == 2){
            kn.themTP(tp);
        }else{
            kn.suaTP(tp);
        }
        if(index == 0 ){
            kn.setTTTP(tp.getMaMA());
        }
        panel.setData();
        this.dispose();
        
    }//GEN-LAST:event_conFirmActionPerformed

    private void addNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNLActionPerformed
        int row=bangNL.getSelectedRow();
        if(row == -1){
            JOptionPane.showConfirmDialog(this,"Click vào nguyên liệu");
            return;
        }else if(slNL.getValue()==null){
            JOptionPane.showConfirmDialog(this,"Nhập số lượng");
            return;
        }
        else if(Double.parseDouble(slNL.getText()) <= 0){
            JOptionPane.showConfirmDialog(this,"Vui lòng không nhập số lượng nhỏ hơn 0");
            return;
        }
        else{
            String maNL=(String) bangNL.getValueAt(row, 0);
            Float sl = ((Number) slNL.getValue()).floatValue();
            boolean kt=false;
            for(int i=0;i<index;i++){
                if(maNL.equals(dsMaNL[i])){
                    dsSLNL[i]+=sl;
                    kt=true;
                    break;
                }
            }
            if(kt==false){
                dsMaNL[index]=maNL;
                dsSLNL[index]=sl;
                dsTenNL[index]=(String) bangNL.getValueAt(row, 1);
                index++;
            }
            setCongThuc();
            tenNL.setText("");
            slNL.setText("");
        }
    }//GEN-LAST:event_addNLActionPerformed

    private void clearNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearNLActionPerformed
        this.dsMaNL = new String[10];
        this.dsSLNL = new Float[10];
        index =0;
        setCongThuc();
        tenNL.setText("");
        slNL.setText("");
    }//GEN-LAST:event_clearNLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThanhPhanDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThanhPhanDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThanhPhanDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThanhPhanDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNL;
    private javax.swing.JTable bangNL;
    private javax.swing.JButton clearNL;
    private javax.swing.JButton conFirm;
    private javax.swing.JTextArea congthuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFormattedTextField slNL;
    private javax.swing.JLabel tenNL;
    // End of variables declaration//GEN-END:variables
}
